source "https://rubygems.org"

chef_version = ENV.fetch("CHEF_VERSION", "11.10")

gem "chef", "~> #{chef_version}"
gem "chefspec", "~> 3.4" if chef_version =~ /^11/

gem "berkshelf", "~> 7.0.2"
gem "foodcritic", "~> 5.0.0"
gem "rake"
gem "rspec", "~> 2.99"
gem "rubocop", "~> 0.23.0"
gem "serverspec", "~> 1.9.0"

group :integration do
  gem "busser-serverspec", "~> 0.2.6"
  gem "kitchen-vagrant", "~> 1.5.1"
  gem "test-kitchen", "~> 2.5.2"
end
